output_dir: ~/git/InductiveQE/experiments

dataset:
  class: InductiveWikiKGDatasetLP
  path: ~/git/InductiveQE/data

task:
  class: InductiveKnowledgeGraphCompletion
  model:
    class: NodePiece
    input_dim: 50
    rel_context: 10
    num_anchors: 20000
    ancs_per_node: 15
    hidden_dims: [50, 50, 50]
    scoring_function: complex
    pooler: cat
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    gnn: True
    use_boundary: False
    use_inverses: True
    wikikg: {{ vocab }}
  criterion: bce
  num_negative: 512
  strict_negative: no
  adversarial_temperature: 1
  sample_weight: no
  batched_eval: True

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 2048
  logger: {{ logger }}

train:
  num_epoch: 2

metric: mrr
fast_test: 1000
save_embs: True
skip_eval_on_train: True
